### Fuzzy Clustering

```{r}
dataScale <- scale(College[sapply(College, is.numeric)])
```

#### Fuzzy k-Means with Entropy regularization and Noise cluster {-}
```{r}
fuzzyValidation <- function(dataScale, seed = 123) {
  # Indici da usare nella validazione
  index_list <- c("SIL.F", "PC", "PE", "MPC", "XB")
  
  run_fkm.ent.noise <- function(index_name) {
    FKM.ent.noise(dataScale, RS = 10, index = index_name, seed = seed)
  }
  
  # Lista con i risultati, ognuno indicizzato per nome
  lstFuzzy <- lapply(index_list, run_fkm.ent.noise)
  names(lstFuzzy) <- index_list
  
  return(lstFuzzy)
}
```

```{r}
results <- fuzzyValidation(dataScale)
```

```{r}
results[["SIL.F"]]$criterion
results[["PC"]]$criterion
results[["PE"]]$criterion
results[["MPC"]]$criterion
results[["XB"]]$criterion


results[["SIL.F"]]$k
results[["PC"]]$k
results[["PE"]]$k
results[["MPC"]]$k
results[["XB"]]$k

```

```{r}
#num_data <- scale(College[sapply(College, is.numeric)])
fkm5 <- FKM.ent.noise(dataScale, k=5, RS=10, seed=123)
head(fkm5$clus)
cl.size(fkm5$U)
Hraw(fkm5$X, fkm5$H)
table(College$Private, fkm5$clus[, 1])
```

```{r}
pairs(dataScale, col=fkm5$clus[, 1], gap=0, pch=16, cex=0.4)
plot.fclust(fkm5, pca=TRUE)
```

```{r}
fkm2 <- FKM.ent.noise(dataScale, k=2, RS=10, seed=123)
head(fkm2$clus)
cl.size(fkm2$U)
Hraw(fkm2$X, fkm2$H)
table(College$Private, fkm2$clus[, 1])
```


```{r}
pairs(dataScale, col=fkm2$clus[, 1], gap=0, pch=16, cex=0.4)
plot.fclust(fkm2, pca=TRUE)
```


#### FK-Med algorithm with Noise cluster (FK MedN algorithm) {-}
```{r}
fkmedn <- FKM.med.noise(dataScale, RS=10, seed=123)
fkmedn$criterion
fkmedn$k
```

```{r}
fkmedn <- FKM.med.noise(dataScale, k=2, RS=10, seed=123)
head(fkmedn$clus)
cl.size(fkmedn$U)
Hraw(fkmedn$X, fkmedn$H)
table(College$Private, fkmedn$clus[, 1])
```

```{r}
pairs(dataScale, col=fkmedn$clus[, 1], gap=0, pch=16, cex=0.4)
plot.fclust(fkmedn, pca=TRUE)
```


