### Hierarchical clustering

```{r}
hcObj <- hierarchicalFunc(df)
```

```{r}
plotHierarchicalCorrTable(hcObj)
```

#### Hierarchical clustering with euclidean distance and average linked method {-}

<div class="hscroll-plot">
<div class='plot-container'>
```{r}
hcObj$best_object$dendrogram()
```
</div>

<div class='plot-container'>
```{r}
hcObj$best_object$elbow(5)
```
</div>

<div class='plot-container'>
```{r}
hcObj$best_object$silhouette()
```
</div>
</div>

##### NbClust function {-}
```{r echo=FALSE}
nbC <- NbClust(df, distance = 'euclidean', min.nc=2, max.nc=10, method = 'average')
```

##### Two clusters {-}

<div class="hscroll-plot" style='height:550px'>
<div class='plot-container'>
```{r}
hcEuclAvg2 <- eclust(df, "hclust", k = 2, hc_metric = "euclidean", hc_method = "average", graph = FALSE)
fviz_dend(hcEuclAvg2, show_labels = FALSE, palette = "jco")
```
</div>

<div class='plot-container'>
```{r message=FALSE}
fviz_cluster(hcEuclAvg2, ellipse.type="norm", geom="point", stand=FALSE, palette="jco", ggtheme=theme_classic())
```
</div>
</div>

<!-- ```{r} -->
<!-- fviz_silhouette(hc, palette="jco", ggthem=theme_classic()) -->
<!-- ``` -->

##### Five clusters {-}
<div class="hscroll-plot" style='height:550px'>
<div class='plot-container'>
```{r}
hcEuclAvg5 <- eclust(df, "hclust", k = 5, hc_metric = "euclidean", hc_method = "average", graph = FALSE)
fviz_dend(hcEuclAvg5, show_labels = FALSE, palette = "jco")
```
</div>

<div class='plot-container'>
```{r message=FALSE}
fviz_cluster(hcEuclAvg5, ellipse.type="norm", geom="point", stand=FALSE, palette="jco", ggthem=theme_classic())
```
</div>
</div>

<!-- ```{r} -->
<!-- fviz_silhouette(hc, palette="jco", ggthem=theme_classic()) -->
<!-- ``` -->

#### Hierarchical clustering with manhattan distance and average linked method {-}

<div class="hscroll-plot">
<div class='plot-container'>
```{r}
hcObj$objects[[7]]$dendrogram()
```
</div>

<div class='plot-container'>
```{r}
hcObj$objects[[7]]$elbow(8)
```
</div>

<div class='plot-container'>
```{r}
hcObj$objects[[7]]$silhouette()
```
</div>
</div>

##### NbClust function {-}
```{r echo=FALSE}
nbC <- NbClust(df, distance = 'manhattan', min.nc=2, max.nc=10, method = 'average')
```

##### Two clusters {-}
<div class="hscroll-plot" style='height:550px'>
<div class='plot-container'>
```{r}
hcManhAvg2 <- eclust(df, "hclust", k = 2, hc_metric = "manhattan", hc_method = "average", graph = FALSE)
fviz_dend(hcManhAvg2, show_labels = FALSE, palette = "jco")
```
</div>

<div class='plot-container'>
```{r message=FALSE}
fviz_cluster(hcManhAvg2, ellipse.type="norm", geom="point", stand=FALSE, palette="jco", ggthem=theme_classic())
```
</div>
</div>

<!-- ```{r} -->
<!-- fviz_silhouette(hc, palette="jco", ggthem=theme_classic()) -->
<!-- ``` -->

##### Eight clusters {-}
<div class="hscroll-plot" style='height:550px'>
<div class='plot-container'>
```{r}
hcManhAvg8 <- eclust(df, "hclust", k = 8, hc_metric = "manhattan", hc_method = "average", graph = FALSE)
fviz_dend(hcManhAvg8, show_labels = FALSE, palette = "jco")
```
</div>

<div class='plot-container'>
```{r message=FALSE}
fviz_cluster(hcManhAvg8, ellipse.type="norm", geom="point", stand=FALSE, palette="jco", ggthem=theme_classic())
```
</div>
</div>

<!-- ```{r} -->
<!-- fviz_silhouette(hc, palette="jco", ggthem=theme_classic()) -->
<!--``` -->

