```{r error=FALSE, message=FALSE, warning=FALSE, results='hide'}

variable <- get(data)[[var]]
if(var == "perc.alumni") {
  variable <- College$perc.alumni[College$perc.alumni > 0]
}

model <- fitDist(variable, type = "realplus", trace=FALSE)
```

<div class="hscroll-plot">
<div class='plot-container'>
```{r results='hide'}
pltMod <- plotHistModel(variable, model)
```
</div>

<div class='plot-container'>
```{r results='hide'}
if (all(is.finite(residuals(pltMod)))) {
  plot(pltMod)
} else {
  warning("Genral plot non eseguito: residui non finiti.")
}
```
</div>

<div class='plot-container'>
```{r results='hide'}
if (all(is.finite(residuals(pltMod)))) {
  suppressWarnings(wp(model, ylim.all = TRUE))
} else {
  warning("Worm plot non eseguito: residui non finiti.")
}
```
</div>
</div>

```{r}
summary(model)
```

```{r}
family_name <- model$family[1]
cdf_function_name <- paste0("p", family_name)
cdf_function <- get(cdf_function_name)

```

```{r}
params <- pltMod[c("mu", "sigma", "nu", "tau")]
params <- params[!sapply(params, is.null)]
```

```{r}
theoretical_cdf <- function(x) {
  do.call(cdf_function, c(list(q = x), params))
}
```

```{r}
ks_test_res <- ks.test(unique(variable), theoretical_cdf, simulate.p.value = TRUE, B = 10000)
```

```{r}
ks_test_res
```
