### `r title` {-}

#### Descriptive statistics {-}

<div class="hscroll-plot">
<div class="plot-container">
```{r}
plotBoxPlot(get(data)[[var]], var)
```

</div>
<div class="plot-container">
```{r}
plotHist(get(data)[[var]], var)
```
</div>
</div>

#### Distribution Fitting {-}
```{r error=FALSE, message=FALSE, warning=FALSE, results='hide'}
model <- fitDist(get(data)[[var]], type = "realplus", trace=FALSE)
```

<div class="hscroll-plot">
<div class='plot-container'>
```{r results='hide'}
pltMod <- plotHistModel(get(data)[[var]], model)
```
</div>

<div class='plot-container'>
```{r results='hide', warning=FALSE}
if (all(is.finite(residuals(pltMod)))) {
  plot(pltMod)
} else {
  warning("Genral plot non eseguito: residui non finiti.")
}
```
</div>

<div class='plot-container'>
```{r results='hide', warning=FALSE}
if (all(is.finite(residuals(pltMod)))) {
  suppressWarnings(wp(model, ylim.all = TRUE))
} else {
  warning("Worm plot non eseguito: residui non finiti.")
}
```
</div>
</div>

```{r}
summary(model)
```
